/*
 * constants.h
 *
 *  Created on: 2 Jan 2021
 *      Author: Roy Dar
 */

#ifndef CONSTANTS_H_
#define CONSTANTS_H_

#define SERVER_CONFIGURATION_FILE_LOCATION "server.info"
#define CLIENT_CONFIGURATION_FILE_LOCATION "me.info"

#define STR_SIZE 255
#define PUBLIC_KEY_SIZE 160
#define PRIVATE_KEY_SIZE 1000
#define CLIENT_ID_SIZE 16
#define MESSAGE_ID_SIZE 4
#define MESSAGE_LENGTH_SIZE 4
#define SYMMETRIC_KEY_SIZE 16
#define EXTRA_MESSAGE_BUFFER 1024

#define MAX_PAYLOAD_BYTES 1024*1024*1024
#define MAX_BYTES_LEN 1024*1024*1024
#define MAX_STR_LEN 1024
#define MAX_MSG_BODY_BYTES 1024*1024*1024

#define BUFFER_SIZE 1024


#define CLIENT_VERSION 1

#define ENCRYPTION_ALGORITHM_AES 1
#define ENCRYPTION_ALGORITHM_RSA 2
#define RSA_KEY_BITS 1024

#define REQUEST_CODE_REGISTER 100
#define REQUEST_CODE_GET_CLIENTS_LIST 101
#define REQUEST_CODE_GET_CLIENT_PUBLIC_KEY 102
#define REQUEST_CODE_SEND_MESSAGE 103
#define REQUEST_CODE_GET_MESSAGES 104

#define MESSAGE_TYPE_ENC_KEY_REQUEST 1
#define MESSAGE_TYPE_ENC_KEY_RESP    2
#define MESSAGE_TYPE_TEXT_MESSAGE    3
#define MESSAGE_TYPE_FILE_MESSAGE    4

#define RESPONSE_CODE_REG_SUCCESS 1000
#define RESPONSE_CODE_CLIENTS_LIST 1001
#define RESPONSE_CODE_CLIENT_PUBLIC_KEY 1002
#define RESPONSE_CODE_MESSAGE_SENT 1003
#define RESPONSE_CODE_LIST_OF_MESSAGES 1004

#define RESPONSE_CODE_GENERAL_ERROR 9000

#endif /* CONSTANTS_H_ */
